players = ["Alan", "Betty", "Charles", "Donna"]

specials = [
    "Use this ticket to make someone else answer a question you draw. They get to keep this ticket if they answer it (but may not replay it).",
    "You may refuse to answer a question, but still keep the ticket. Once played you must discard this ticket.",
    "Ask a direct question of your choice to any player. They must answer, but get to keep this ticket if they answer satisfyingly.",
    "Declare your superhero name. If at any time someone calls you by your real name you may steal a ticket from them.",
    "Pick any player. They are to address you as 'Sir' or 'Madam' for the next ten minutes. If they forget they forfeit a ticket to you.",
    "Keep this ticket till tomorrow, when you can redeem it for a favor of your choosing from your partner.",
    "Take control of the music for the next 10 minutes and play whatever you want.",
]

party_qs = [
    "What's the most ridiculous thing you've ever believed as a kid?",
    "If you could instantly master any skill, what would it be?",
    "What's the strangest food you've ever eaten?",
    "What's the most awkward moment you've experienced in public?",
    "If you could live in any fictional universe, where would it be?",
    "What's the worst fashion trend you ever followed?",
    "Who would play you in a movie about your life, and why?",
    "If you could switch lives with anyone for a day, who would it be?",
    "What's the most bizarre compliment you've ever received?",
    "What's a talent you have that nobody knows about?",
    "What's the most spontaneous thing you've ever done?",
    "If you had to relive one day of your life forever, which day would it be?",
    "What's the most questionable purchase you've ever made?",
    "What song do you secretly love but would never admit to?",
    "If you were a superhero, what ridiculous superpower would you want?",
    "What's the weirdest thing you've ever Googled?",
    "What's your favorite childhood memory that still makes you laugh?",
    "If you could erase one trend from history, what would it be?",
    "What's the funniest or most surprising thing a child has ever said to you?",
    "If you were a flavor of ice cream, what flavor would you be and why?",
    "What's the worst excuse you've ever used to get out of something?",
    "If your life had a theme song, what would it be?",
    "What's the most over-the-top thing you've ever done for a crush?",
    "What's the weirdest dream you've ever had?",
    "If you could invite any three people (dead or alive) to dinner, who would they be?",
    "What's a secret talent you wish you had?",
    "What's your guilty pleasure TV show or movie?",
    "If you could have any animal (real or mythical) as a pet, what would it be?",
    "What's the most useless thing you're really good at?",
    "What's the weirdest coincidence you've ever experienced?",
    "If you could only eat one meal for the rest of your life, what would it be?",
    "What's the most random item you always carry with you?",
    "What's the most awkward or unexpected thing you've said in an important moment?",
    "If you could time travel, would you go to the past or the future? Why?",
    "What's the funniest nickname you've ever been given?",
    "What's a trend or fad you really regret being part of?",
    "If you were a contestant on a reality show, which one would it be?",
    "What's the worst gift you've ever received?",
    "What's something you've done that no one believes when you tell them?",
    "If you could instantly swap careers, what job would you choose?",
    "What's the most adventurous thing you've ever done?",
    "If you were stranded on a desert island, what three things would you bring?",
    "What's the weirdest superstition you believe in or have heard of?",
    "If you could create a new holiday, what would it be about?",
    "What's the worst piece of advice you've ever received?",
    "If you could have dinner with a fictional character, who would it be?",
    "What's a skill you've tried and failed to learn?",
    "What's your favorite joke or pun?",
    "If you could trade places with anyone in history, who would it be?",
    "What's the most memorable thing you've overheard in public?",
    "If you could magically understand one language, which would it be?",
    "What's the most out-of-character thing you've ever done?",
    "What's the weirdest or most unusual fact you know?",
    "If your pet could talk, what do you think it would say about you?",
    "What's the most unusual thing you've ever found?",
    "If you could live in any time period, which one would you choose?",
    "What's a lie you told as a child that you still feel guilty about?",
    "What's the funniest thing that's ever happened on a family vacation?",
    "If you could only wear one color for the rest of your life, what would it be?",
    "What's the most awkward text you've ever sent to the wrong person?",
]
